logging:
  level:
    org.springframework: DEBUG
    org.springframework.cloud.gateway: TRACE

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-producto
          uri: https://service-producto.azurewebsites.net
          predicates:
            - Path=/api/almacen/**
          filters:
            - StripPrefix=2
        - id: service-empleado
          uri: https://service-empleado.azurewebsites.net
          predicates:
            - Path=/api/rrhh/**
          filters:
            - StripPrefix=2
        - id: service-doc-compra
          uri: https://service-doc-compra.azurewebsites.net
          predicates:
            - Path=/api/doc-compra/**
          filters:
            - StripPrefix=2
        - id: service-cotizacion
          uri: https://service-cotizacion.azurewebsites.net
          predicates:
            - Path=/api/cotizacion/**
          filters:
            - StripPrefix=2
        - id: service-cliente
          uri: http://localhost:3001
          predicates:
            - Path=/api/cliente/**
          filters:
            - StripPrefix=2
        - id: service-pedido
          uri: http://localhost:3002
          predicates:
            - Path=/api/pedido/**
          filters:
            - StripPrefix=2
        - id: service-proveedor
          uri: https://service-proveedor.azurewebsites.net
          predicates:
            - Path=/api/proveedor/**
          filters:
            - StripPrefix=2
        - id: service-factura-venta
          uri: http://localhost:3003
          predicates:
            - Path=/api/facturaventa/**
          filters:
            - StripPrefix=2

server:
  port: ${PORT:9000}